const explainComplications = [
    "Standing on one leg",
    "Whispering",
    "Without using words starting with T",
    "With your hands behind your back",
    "Singing the explanation",
    "As if you are very cold",
    "As if you are very hot",
    "Like a robot",
    "Like a news anchor",
    "Very slowly",
    "Shouting everything",
    "In a very high-pitched voice",
    "In a deep, scary voice",
    "Like an opera singer",
    "Rapping the explanation",
    "Like a sports commentator",
    "Like an auctioneer (very fast)",
    "Stuttering on every word",
    "Like a drill sergeant",
    "Like a sleepy bedtime storyteller",
    "With a heavy fake accent",
    "Like a pirate",
    "Like a cowboy",
    "Like an alien trying to speak human",
    "Like a medieval knight",
    "Like a royal queen/king",
    "Like a stereotypical nerd",
    "Like a surfer dude",
    "Like a strict teacher",
    "Like a politician making a speech",
    "While doing jumping jacks",
    "While doing squats",
    "While running in place",
    "Lying on your back",
    "Lying on your stomach",
    "While spinning around",
    "With your tongue sticking out",
    "Clenching your teeth together",
    "Holding your nose",
    "With your fingers in your ears",
    "While applauding constantly",
    "Facing the wall (back to players)",
    "Sitting under the table",
    "While doing a plank",
    "While marching like a soldier",
    "While pretending to drive a car",
    "While pretending to lift weights",
    "With your eyes wide open (no blinking)",
    "While constantly nodding",
    "While shaking your head 'no'",
    "While crying hysterically",
    "While laughing uncontrollably",
    "As if you are incredibly bored",
    "As if you are very suspicious",
    "As if you are terrified",
    "As if you are incredibly angry",
    "As if you are heartbroken",
    "As if you are extremely shy",
    "As if you are drunk",
    "As if you are out of breath",
    "As if you just ate something spicy",
    "As if you are telling a secret",
    "As if you are pleading for your life",
    "As if you are complaining to a manager",
    "As if you are bragging",
    "As if you are flirting",
    "As if you are a toddler",
    "As if you are a very old person",
    "As if you are confused",
    "As if you are disgusted",
    "Only using nouns",
    "Without using verbs",
    "Without using the letter 'E'",
    "Without using the letter 'S'",
    "Using only one-syllable words",
    "Start every sentence with 'Sadly...'",
    "Start every sentence with 'Imagine...'",
    "End every sentence with '...cha-cha-cha'",
    "Rhyming your sentences",
    "Speaking in questions only?",
    "Repeating every word twice",
    "Inserting the word 'banana' between words",
    "Without saying 'yes' or 'no'",
    "Using only 3 words at a time",
    "Spelling out every third word",
    "Counting to 3 between every word",
    "Speaking as if inhaling helium",
    "Without opening your mouth wide",
    "Like you have a hot potato in your mouth",
    "Speaking in third person ('He says...')",
    "Like you are underwater",
    "Like you are in a library",
    "Like you are at a rock concert",
    "Like you are on a rollercoaster",
    "Like you are defusing a bomb",
    "Like you are reporting a crime",
    "Like you are proposing marriage",
    "Like you are firing someone",
    "Like you are ordering at a drive-thru",
    "Like you are talking to a pet"
];

const showComplications = [
    "With eyes closed",
    "Using only one hand",
    "In slow motion",
    "Sitting on a chair",
    "Without moving your feet",
    "As if you are underwater",
    "Using only your fingers",
    "With a straight face",
    "Jumping while showing",
    "Lying on the floor",
    "Without using your hands (arms only)",
    "Using only your left hand",
    "Using only your right hand",
    "With your elbows glued to your ribs",
    "With your knees tied together (imaginary)",
    "Using only your head and neck",
    "Using only your legs/feet",
    "With one hand behind your back",
    "With both hands clasped together",
    "Without bending your elbows",
    "Without bending your knees",
    "While holding your ankles",
    "While crossing your fingers",
    "With your palms open flat",
    "With your hands in fists",
    "Using only your pinky fingers",
    "While hugging yourself",
    "While plugging your ears",
    "While covering one eye",
    "While biting your lip",
    "While sitting on the floor",
    "While lying on your stomach",
    "While kneeling",
    "While standing on one leg",
    "While squatting",
    "While doing a plank",
    "While walking backwards",
    "While spinning in circles",
    "While hopping like a bunny",
    "While crawling on all fours",
    "While doing lunges",
    "While standing on a chair (carefully)",
    "While leaning against a wall",
    "While sitting cross-legged",
    "In a fetal position",
    "While tiptoeing",
    "While slouching heavily",
    "With your back to the audience",
    "While headbanging",
    "While trembling/shaking",
    "Like a broken robot",
    "Like a graceful ballerina",
    "Like a zombie",
    "Like a ninja",
    "Like a classic mime (trapped in box)",
    "Like a puppet on strings",
    "Like a ragdoll",
    "Like a sumo wrestler",
    "Like a boxer",
    "Like a heavy metal guitarist",
    "Like a runway model",
    "Like a scared cat",
    "Like a monkey",
    "Like a T-Rex (short arms)",
    "Like a chicken",
    "Like a penguin",
    "Like a snake",
    "Like a giant/monster",
    "In the style of a silent movie",
    "In the style of an action movie",
    "As if in zero gravity",
    "As if walking against strong wind",
    "As if on slippery ice",
    "As if the floor is hot lava",
    "As if moving through sticky honey",
    "As if holding something very heavy",
    "As if holding something very fragile",
    "As if you are melting",
    "As if you are freezing",
    "As if you are burning",
    "As if you are being electrocuted",
    "As if you are magnetic",
    "As if you are invisible",
    "As if experiencing an earthquake",
    "As if you are very tiny",
    "As if you are gigantic",
    "As if your clothes are too tight",
    "As if your shoes are too big",
    "As if you are stuck in a spiderweb",
    "As if you are floating in water",
    "In fast forward (very fast)",
    "In rewind (actions backwards)",
    "Like a glitchy video",
    "Stop-motion animation style",
    "Freezing every 3 seconds",
    "Looping the same 2 seconds",
    "Only moving when someone claps",
    "Moving in sync with a heartbeat",
    "Like a broken clock",
    "Extremely slowly (sloth style)"
];

export { explainComplications, showComplications };